image: composer:latest
definitions:
  caches:
    vendor: vendor
pipelines:
  default:
    - step:
        name: Composer validation
        script:
          - composer self-update
          - composer check-platform-reqs
          - composer validate --strict --no-interaction

    - step:
        name: Testing suite
        caches:
          - composer
          - vendor
        script:
          - composer self-update
          - if [ -n "$COMPOSER_PRE_INSTALL_CALLBACK" ]; then eval $COMPOSER_PRE_INSTALL_CALLBACK; fi
          - composer install --dev --prefer-dist --no-scripts --no-progress --optimize-autoloader --no-interaction -vvv
          - composer show
          - composer exec -v grumphp run
          - curl -LSs https://codecov.io/bash | bash

    - step:
        name: Push to GitHub
        script:
          - git remote add github $GITHUB_REMOTE
          - git push github master --tags

  tags:
    '*':
      - step:
          name: Push tags to Github
          script:
            - git remote add github $GITHUB_REMOTE
            - git push github --tags
